"""Added score column to User model

Revision ID: 484b012a6f25
Revises: 
Create Date: 2024-07-04 14:37:21.279234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484b012a6f25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
